# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  
  ## use insecure key
  config.ssh.insert_key = false
  
  # turnm off synced folder which is the current working directoru and /vagrant directory in VM
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.provider :virtualbox do |v|
	v.memory = 256
	v.linked_clone = true
  end
	
  config.vm.define "app1" do |app|
	app.vm.hostname = "orc.app1.test"
	app.vm.network "private_network", ip: "192.168.60.4"
  end	
  
  
  config.vm.define "app2" do |app|
	app.vm.hostname = "orc.app2.test"
	app.vm.network "private_network", ip: "192.168.60.5"
  end	
  
  
  config.vm.define "app3" do |db|
	db.vm.hostname = "orc.app3.test"
	db.vm.network "private_network", ip: "192.168.60.6"
  end	
  
end
